main: us.zingalicio.cordstone.Cordstone
name: Cordstone
version: ${project.version}
description: ${project.description}
depends: [PermissionsEx, PowerNBT]
author: zingten11
database: false
commands:
  cordstone:
    aliases: [cs]
